environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "5"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - npm install -g npm@3.x-latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm prune
test_script:
  - node --version
  - npm --version
  # npm script for windows test
  - npm run test:win
# GO_FAST
matrix:
  fast_finish: true
# we don't need the builds, we just need tests
build: off
